In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [41]:
data = pd.read_csv("Social_Network_Ads.csv")

In [42]:
data.head(2)

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0

In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
from sklearn.ensemble import RandomForestClassifier

In [46]:
X = data.iloc[:,:-1].values

In [47]:
y = data.iloc[:,-1].values

In [48]:
X[0],y[0]

(array([   19, 19000]), 0)

In [49]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=101)

In [50]:
scaler = StandardScaler()

In [51]:
X_train = scaler.fit_transform(X_train)

In [52]:
X_test = scaler.transform(X_test)

In [53]:
classifier_0 = RandomForestClassifier(n_estimators=10,criterion="entropy",random_state=101)
classifier_1 = RandomForestClassifier(n_estimators=10,criterion="gini",random_state=101)

In [54]:
classifier_0.fit(X_train,y_train)
classifier_1.fit(X_train,y_train)

RandomForestClassifier(n_estimators=10, random_state=101)

In [55]:
pred0 = classifier_0.predict(X_test)
pred1 = classifier_1.predict(X_test)

In [56]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [57]:
print(classification_report(y_test,pred0))
print(confusion_matrix(y_test,pred0))
print(accuracy_score(y_test,pred0))

              precision    recall  f1-score   support

           0       0.98      0.91      0.94        54
           1       0.83      0.96      0.89        26

    accuracy                           0.93        80
   macro avg       0.91      0.93      0.92        80
weighted avg       0.93      0.93      0.93        80

[[49  5]
 [ 1 25]]
0.925


In [58]:
print(classification_report(y_test,pred1))
print(confusion_matrix(y_test,pred1))
print(accuracy_score(y_test,pred1))

              precision    recall  f1-score   support

           0       0.98      0.91      0.94        54
           1       0.83      0.96      0.89        26

    accuracy                           0.93        80
   macro avg       0.91      0.93      0.92        80
weighted avg       0.93      0.93      0.93        80

[[49  5]
 [ 1 25]]
0.925
